# Generated by Django 5.2.11 on 2026-02-18 12:44

import django.db.models.deletion
import planner.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country_code', models.CharField(max_length=2)),
                ('city_name', models.CharField(max_length=128)),
                ('airport_code', models.CharField(max_length=8)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('rank', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['rank', 'city_name'],
            },
        ),
        migrations.CreateModel(
            name='FlightOption',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=32)),
                ('external_offer_id', models.CharField(max_length=128)),
                ('origin_airport', models.CharField(max_length=8)),
                ('destination_airport', models.CharField(max_length=8)),
                ('departure_at', models.DateTimeField(blank=True, null=True)),
                ('return_at', models.DateTimeField(blank=True, null=True)),
                ('airline_codes', models.JSONField(blank=True, default=list)),
                ('stops', models.PositiveSmallIntegerField(default=0)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('cabin_class', models.CharField(default='economy', max_length=32)),
                ('currency', models.CharField(max_length=3)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deeplink_url', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_options', to='planner.destinationcandidate')),
            ],
            options={
                'ordering': ['total_price'],
            },
        ),
        migrations.CreateModel(
            name='HotelOption',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=32)),
                ('external_offer_id', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('star_rating', models.FloatField(default=0)),
                ('guest_rating', models.FloatField(default=0)),
                ('neighborhood', models.CharField(blank=True, max_length=128)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('currency', models.CharField(max_length=3)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deeplink_url', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_options', to='planner.destinationcandidate')),
            ],
            options={
                'ordering': ['total_price'],
            },
        ),
        migrations.CreateModel(
            name='PlanRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin_input', models.CharField(max_length=64)),
                ('origin_code', models.CharField(max_length=8)),
                ('destination_country', models.CharField(db_index=True, max_length=2)),
                ('date_mode', models.CharField(choices=[('exact', 'Exact dates'), ('flexible', 'Month and flexibility')], default='exact', max_length=16)),
                ('depart_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('travel_month', models.DateField(blank=True, null=True)),
                ('flexibility_days', models.PositiveSmallIntegerField(default=0)),
                ('nights_min', models.PositiveSmallIntegerField(default=3)),
                ('nights_max', models.PositiveSmallIntegerField(default=7)),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('travelers', models.PositiveSmallIntegerField(default=1)),
                ('search_currency', models.CharField(default='USD', max_length=3)),
                ('hotel_filters', models.JSONField(blank=True, default=dict)),
                ('flight_filters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('searching_flights', 'Searching flights'), ('searching_hotels', 'Searching hotels'), ('building_packages', 'Building packages'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='queued', max_length=32)),
                ('progress_message', models.CharField(blank=True, max_length=255)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('public_token', models.CharField(db_index=True, default=planner.models.token_hex, max_length=32, unique=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageOption',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.PositiveSmallIntegerField(default=0)),
                ('currency', models.CharField(max_length=3)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('score', models.FloatField(default=0)),
                ('price_score', models.FloatField(default=0)),
                ('convenience_score', models.FloatField(default=0)),
                ('quality_score', models.FloatField(default=0)),
                ('explanations', models.JSONField(blank=True, default=list)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_options', to='planner.destinationcandidate')),
                ('flight_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_options', to='planner.flightoption')),
                ('hotel_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_options', to='planner.hoteloption')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_options', to='planner.planrequest')),
            ],
            options={
                'ordering': ['rank', '-score'],
            },
        ),
        migrations.AddField(
            model_name='hoteloption',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_options', to='planner.planrequest'),
        ),
        migrations.AddField(
            model_name='flightoption',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_options', to='planner.planrequest'),
        ),
        migrations.AddField(
            model_name='destinationcandidate',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_candidates', to='planner.planrequest'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_origin', models.CharField(blank=True, max_length=16)),
                ('preferred_currency', models.CharField(default='USD', max_length=3)),
                ('default_budget_min', models.DecimalField(decimal_places=2, default=Decimal('800.00'), max_digits=10)),
                ('default_budget_max', models.DecimalField(decimal_places=2, default=Decimal('3500.00'), max_digits=10)),
                ('travel_preferences', models.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProviderError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=64)),
                ('context', models.CharField(blank=True, max_length=128)),
                ('error_message', models.TextField()),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_errors', to='planner.planrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='planner.packageoption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_packages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='packageoption',
            index=models.Index(fields=['plan', 'rank'], name='planner_pac_plan_id_a821a0_idx'),
        ),
        migrations.AddIndex(
            model_name='packageoption',
            index=models.Index(fields=['plan', 'score'], name='planner_pac_plan_id_26a6d9_idx'),
        ),
        migrations.AddIndex(
            model_name='hoteloption',
            index=models.Index(fields=['plan', 'provider'], name='planner_hot_plan_id_5467de_idx'),
        ),
        migrations.AddIndex(
            model_name='hoteloption',
            index=models.Index(fields=['plan', 'total_price'], name='planner_hot_plan_id_a324d5_idx'),
        ),
        migrations.AddIndex(
            model_name='flightoption',
            index=models.Index(fields=['plan', 'provider'], name='planner_fli_plan_id_af6a3f_idx'),
        ),
        migrations.AddIndex(
            model_name='flightoption',
            index=models.Index(fields=['plan', 'total_price'], name='planner_fli_plan_id_aca787_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='destinationcandidate',
            unique_together={('plan', 'airport_code')},
        ),
        migrations.AddIndex(
            model_name='providererror',
            index=models.Index(fields=['plan', 'provider'], name='planner_pro_plan_id_b4ff23_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedpackage',
            unique_together={('user', 'package')},
        ),
    ]
