# Generated by Django 5.2.11 on 2026-02-18 13:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flightoption',
            name='amount_minor',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flightoption',
            name='last_checked_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='hoteloption',
            name='amount_minor',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hoteloption',
            name='distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hoteloption',
            name='last_checked_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='packageoption',
            name='amount_minor',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='packageoption',
            name='last_scored_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='packageoption',
            name='location_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='packageoption',
            name='score_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='providererror',
            name='error_type',
            field=models.CharField(choices=[('timeout', 'Timeout'), ('rate_limit', 'Rate limit'), ('auth', 'Auth'), ('quota', 'Quota'), ('parse', 'Parse'), ('empty', 'Empty'), ('unknown', 'Unknown')], default='unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='providererror',
            name='http_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providererror',
            name='provider_latency_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=64)),
                ('url', models.TextField()),
                ('clicked_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='click_events', to='planner.packageoption')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='click_events', to='planner.planrequest')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='click_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=64)),
                ('external_conversion_id', models.CharField(blank=True, max_length=128)),
                ('amount_minor', models.BigIntegerField(default=0)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('click', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to='planner.clickevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_currency', models.CharField(max_length=3)),
                ('quote_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('as_of', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(default='fallback', max_length=32)),
            ],
            options={
                'ordering': ['-as_of'],
                'indexes': [models.Index(fields=['base_currency', 'quote_currency'], name='planner_fxr_base_cu_f592d8_idx'), models.Index(fields=['as_of'], name='planner_fxr_as_of_4e444f_idx')],
                'unique_together': {('base_currency', 'quote_currency')},
            },
        ),
        migrations.CreateModel(
            name='ProviderCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(db_index=True, max_length=64)),
                ('success', models.BooleanField(default=False)),
                ('error_type', models.CharField(choices=[('timeout', 'Timeout'), ('rate_limit', 'Rate limit'), ('auth', 'Auth'), ('quota', 'Quota'), ('parse', 'Parse'), ('empty', 'Empty'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_calls', to='planner.planrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='clickevent',
            index=models.Index(fields=['provider', 'clicked_at'], name='planner_cli_provide_1506c0_idx'),
        ),
        migrations.AddIndex(
            model_name='clickevent',
            index=models.Index(fields=['plan', 'clicked_at'], name='planner_cli_plan_id_ae199a_idx'),
        ),
        migrations.AddIndex(
            model_name='conversionevent',
            index=models.Index(fields=['provider', 'created_at'], name='planner_con_provide_929c99_idx'),
        ),
        migrations.AddIndex(
            model_name='providercall',
            index=models.Index(fields=['provider', 'created_at'], name='planner_pro_provide_ea6420_idx'),
        ),
        migrations.AddIndex(
            model_name='providercall',
            index=models.Index(fields=['provider', 'success', 'created_at'], name='planner_pro_provide_4f61dc_idx'),
        ),
    ]
