# Generated by Django 5.2.11 on 2026-02-19 18:03

import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_flightoption_amount_minor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clickevent',
            name='correlation_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='clickevent',
            name='destination',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='clickevent',
            name='link_type',
            field=models.CharField(choices=[('flight', 'Flight'), ('hotel', 'Hotel'), ('tour', 'Tour'), ('other', 'Other')], db_index=True, default='other', max_length=16),
        ),
        migrations.AddField(
            model_name='clickevent',
            name='outbound_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='destinationcandidate',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='packageoption',
            name='estimated_flight_max',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='packageoption',
            name='estimated_flight_min',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='packageoption',
            name='estimated_hotel_nightly_max',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='packageoption',
            name='estimated_hotel_nightly_min',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='packageoption',
            name='estimated_total_max',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='packageoption',
            name='estimated_total_min',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='packageoption',
            name='flight_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='packageoption',
            name='freshness_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='packageoption',
            name='hotel_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='packageoption',
            name='tours_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='planrequest',
            name='preference_weights',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name='clickevent',
            index=models.Index(fields=['link_type', 'clicked_at'], name='planner_cli_link_ty_92aef0_idx'),
        ),
    ]
