# Generated by Django 5.2.11 on 2026-02-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_clickevent_correlation_id_clickevent_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationcandidate',
            name='timezone',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='packageoption',
            name='data_confidence',
            field=models.FloatField(default=0.75),
        ),
        migrations.AddField(
            model_name='packageoption',
            name='flight_entities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='packageoption',
            name='hotel_entities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='packageoption',
            name='place_entities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='packageoption',
            name='tour_entities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='planrequest',
            name='adults',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='planrequest',
            name='children',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planrequest',
            name='departure_date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planrequest',
            name='departure_date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planrequest',
            name='destination_iata',
            field=models.CharField(blank=True, db_index=True, max_length=3),
        ),
        migrations.AddField(
            model_name='planrequest',
            name='destination_iatas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='planrequest',
            name='destination_input',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='planrequest',
            name='explore_constraints',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='planrequest',
            name='origin_iata',
            field=models.CharField(blank=True, db_index=True, max_length=3),
        ),
        migrations.AddField(
            model_name='planrequest',
            name='search_mode',
            field=models.CharField(choices=[('direct', 'Direct destination'), ('explore', 'Explore destinations')], db_index=True, default='direct', max_length=16),
        ),
        migrations.AddField(
            model_name='planrequest',
            name='trip_length_max',
            field=models.PositiveSmallIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='planrequest',
            name='trip_length_min',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='planrequest',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('validating', 'Validating'), ('expanding_destinations', 'Expanding destinations'), ('fetching_flight_signals', 'Fetching flight signals'), ('fetching_hotel_signals', 'Fetching hotel signals'), ('fetching_tours', 'Fetching tours'), ('fetching_places', 'Fetching places'), ('scoring', 'Scoring'), ('searching_flights', 'Searching flights'), ('searching_hotels', 'Searching hotels'), ('building_packages', 'Building packages'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='queued', max_length=32),
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('iata', models.CharField(db_index=True, max_length=3, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(db_index=True, max_length=128)),
                ('country', models.CharField(db_index=True, max_length=128)),
                ('country_code', models.CharField(blank=True, db_index=True, max_length=2)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=64)),
                ('search_blob', models.CharField(blank=True, db_index=True, max_length=512)),
            ],
            options={
                'ordering': ['iata'],
                'indexes': [models.Index(fields=['iata', 'city'], name='planner_air_iata_09fe6e_idx'), models.Index(fields=['city', 'country'], name='planner_air_city_119778_idx'), models.Index(fields=['name'], name='planner_air_name_2d871b_idx')],
            },
        ),
    ]
