# Generated by Codex on 2026-02-21

from django.db import migrations


def backfill_planrequest_airport_fields(apps, schema_editor):  # noqa: ARG001
    PlanRequest = apps.get_model("planner", "PlanRequest")
    for plan in PlanRequest.objects.all().iterator():
        updates = []
        if not plan.origin_iata and plan.origin_code:
            plan.origin_iata = (plan.origin_code or "")[:3].upper()
            updates.append("origin_iata")
        if not plan.destination_input and plan.destination_country:
            plan.destination_input = (plan.destination_country or "").upper()
            updates.append("destination_input")
        if not plan.trip_length_min:
            plan.trip_length_min = max(1, int(plan.nights_min or 1))
            updates.append("trip_length_min")
        if not plan.trip_length_max:
            plan.trip_length_max = max(plan.trip_length_min, int(plan.nights_max or plan.trip_length_min))
            updates.append("trip_length_max")
        if not plan.adults:
            plan.adults = max(1, int(plan.travelers or 1))
            updates.append("adults")
        if plan.children is None:
            plan.children = 0
            updates.append("children")
        if not plan.departure_date_from and plan.depart_date:
            plan.departure_date_from = plan.depart_date
            updates.append("departure_date_from")
        if not plan.departure_date_to and plan.depart_date:
            plan.departure_date_to = plan.depart_date
            updates.append("departure_date_to")
        if updates:
            plan.save(update_fields=updates)


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0004_destinationcandidate_timezone_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_planrequest_airport_fields, migrations.RunPython.noop),
    ]
