# Generated by Django 5.2.11 on 2026-02-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_backfill_airport_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickevent',
            name='link_type',
            field=models.CharField(choices=[('flight', 'Flight'), ('hotel', 'Hotel'), ('tour', 'Tour'), ('place', 'Place'), ('other', 'Other')], db_index=True, default='other', max_length=16),
        ),
    ]
