# Generated by Django 5.2.11 on 2026-02-21 10:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_alter_clickevent_link_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='planrequest',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='planrequest',
            constraint=models.UniqueConstraint(fields=('user', 'idempotency_key'), name='planner_planrequest_user_idempotency_key_unique'),
        ),
    ]
