# Generated by Django 5.2.11 on 2026-02-22 18:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_planrequest_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightoption',
            name='link_confidence',
            field=models.FloatField(default=0.7),
        ),
        migrations.AddField(
            model_name='flightoption',
            name='link_rationale',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='flightoption',
            name='link_type',
            field=models.CharField(default='search', max_length=16),
        ),
        migrations.AddField(
            model_name='hoteloption',
            name='link_confidence',
            field=models.FloatField(default=0.55),
        ),
        migrations.AddField(
            model_name='hoteloption',
            name='link_rationale',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hoteloption',
            name='link_type',
            field=models.CharField(default='search', max_length=16),
        ),
        migrations.AddField(
            model_name='hoteloption',
            name='provider_property_id',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='packageoption',
            name='component_links',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='packageoption',
            name='component_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='packageoption',
            name='price_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='packageoption',
            name='selected_tour_option_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='TourOption',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=32)),
                ('external_product_id', models.CharField(db_index=True, max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('amount_minor', models.BigIntegerField(default=0)),
                ('deeplink_url', models.TextField(blank=True)),
                ('link_type', models.CharField(default='search', max_length=16)),
                ('link_confidence', models.FloatField(default=0.45)),
                ('link_rationale', models.CharField(blank=True, max_length=255)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('last_checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_options', to='planner.destinationcandidate')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_options', to='planner.planrequest')),
            ],
            options={
                'ordering': ['total_price', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='packageoption',
            name='tour_options',
            field=models.ManyToManyField(blank=True, related_name='package_options', to='planner.touroption'),
        ),
        migrations.AddIndex(
            model_name='touroption',
            index=models.Index(fields=['plan', 'provider'], name='planner_tou_plan_id_272279_idx'),
        ),
        migrations.AddIndex(
            model_name='touroption',
            index=models.Index(fields=['plan', 'candidate'], name='planner_tou_plan_id_8b89fd_idx'),
        ),
    ]
