# Generated by Django 5.2.11 on 2026-02-22 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_flightoption_link_confidence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('country', models.CharField(blank=True, max_length=128, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(default='manual', max_length=32)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1500, null=True)),
                ('outbound_url', models.URLField(blank=True, max_length=1500, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_places', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='planner_sav_user_id_da9fb0_idx'), models.Index(fields=['user', 'source'], name='planner_sav_user_id_8df8bc_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('user', 'external_id'), name='planner_savedplace_user_external_id_unique'), models.UniqueConstraint(condition=models.Q(('external_id__isnull', True)), fields=('user', 'name', 'city', 'country'), name='planner_savedplace_user_name_city_country_unique')],
            },
        ),
    ]
